name: dataproxy-upload
description: Upload a file to ebrains dataproxy
author: "Xiao Gui <xgui3783@gmail.com>"
inputs:
  upload-file:
    required: true
    description: File to upload
  bucket-name:
    required: true
    description: Bucket name
  dest-path:
    required: true
    description: Destination path
  client-id:
    required: true
    description: Client ID used for client credential flow
  client-secret:
    required: true
    description: Client Secret used for client credential flow
runs:
  using: docker
  entrypoint: /bin/bash
  args:
    - "-c"
    - |
      ebrains_util iam auth login \
        --scope team \
        --client-id ${{ inputs.client-id }} \
        --client-secret ${{ inputs.client-secret }}
      ebrains_util bucket -n ${{ inputs.bucket-name }} \
        upload --progress \
        ${{ inputs.upload-file }} \
        ${{ inputs.dest-path }}
  image: Dockerfile
