- name: "Provision node"
  hosts: localhost
  
  vars:
    LINODE_TOKEN: XXX
    LINODE_REGION: XXX

  tasks:

  - name: "Validate"
    assert:
      that:
      - "LINODE_TOKEN != 'XXX'"
      - "LINODE_REGION != 'XXX'"
      fail_msg: |
        Inputs must be provided:

        - LINODE_TOKEN
        - LINODE_REGION

  - name: Provision
    shell: |
      LINODE_ROOTPASS=$(tr -dc A-Za-z0-9 </dev/urandom | head -c 13)
      
      provision_result=$(curl \
          --fail-with-body \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer {{ LINODE_TOKEN }}" \
          -X POST -d '{
              "image": "linode/ubuntu24.04",
              "private_ip": false,
              "region": "{{ LINODE_REGION }}",
              "type": "g6-nanode-1",
              "label": "ubuntu-{{ LINODE_REGION }}",
              "root_pass": "'$LINODE_ROOTPASS'",
              "authorized_users": [
                  "xgui3783"
              ],
              "disk_encryption": "disabled"
          }' https://api.linode.com/v4/linode/instances)

      if [[ "$?" != "0" ]]
      then
          echo "Create linode failed"
          exit 1
      fi

      echo $provision_result | jq -r '.id'

    become: false
    args:
      executable: /bin/bash
    changed_when: false
    register: provision_output

  - name: "set linode id"
    set_fact:
      LINODE_ID: "{{ provision_output.stdout }}"
  
  - name: "debug"
    debug: 
      msg:
      - "Linode ID: {{ LINODE_ID }}"