name: "[ebrain debug] [adhoc] debug infra"

on:
  push:
    paths:
      - '.github/workflows/ebrains.debug.infra.yml'
jobs:
  debug-ebrains-infra:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Debug TLS
      run: |
        curl -v https://docker-registry.ebrains.eu/v2/
