# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[ebrain services] [10min] OAuth v2"

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    env:
      OAUTH_V2_CLIENT_ID: ${{ secrets.OAUTH_V2_CLIENT_ID }}
      OAUTH_V2_REDIRECT_URL: ${{ secrets.OAUTH_V2_REDIRECT_URL }}
      OAUTH_V2_SCOPES: ${{ secrets.OAUTH_V2_SCOPES }}
      OAUTH_V2_ENDPOINT: ${{ secrets.OAUTH_V2_ENDPOINT }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run mocha -- './ebrains_services/oauth.spec.js'
