# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[ebrain services] [30min] DOI Redirect"

on:
  schedule:
    - cron: '*/30 * * * *'

env:
  SIIBRA_MONITORING_DOI_REDIRECT: ${{ secrets.SIIBRA_MONITORING_DOI_REDIRECT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i
    - run: ./node_modules/.bin/cypress run -s ./cypress/e2e/ebrains-doi.cy.js
    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_DOI_REDIRECT" ]
        then
          curl "$SIIBRA_MONITORING_DOI_REDIRECT"
        fi
