# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[ebrain services] [10min] OAuth v2"

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      OAUTH_V2_CLIENT_ID: ${{ secrets.OAUTH_V2_CLIENT_ID }}
      OAUTH_V2_REDIRECT_URL: ${{ secrets.OAUTH_V2_REDIRECT_URL }}
      OAUTH_V2_SCOPES: ${{ secrets.OAUTH_V2_SCOPES }}
      OAUTH_V2_ENDPOINT: ${{ secrets.OAUTH_V2_ENDPOINT }}
      VOLUBA_OAUTH_V2_CLIENT_ID: ${{ secrets.VOLUBA_OAUTH_V2_CLIENT_ID }}
      VOLUBA_OAUTH_V2_REDIRECT_URL: ${{ secrets.VOLUBA_OAUTH_V2_REDIRECT_URL }}
      VOLUBA_OAUTH_V2_SCOPES: ${{ secrets.VOLUBA_OAUTH_V2_SCOPES }}
      VOLUBA_OAUTH_V2_ENDPOINT: ${{ secrets.VOLUBA_OAUTH_V2_ENDPOINT }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install pytest requests
    - run: pytest -svvv ./ebrains_services/test_ebrains_oauth.py