# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[ebrain services] [10min] OAuth v2"

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  SIIBRA_MONITORING_OAUTH: ${{ secrets.SIIBRA_MONITORING_OAUTH }}

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      OAUTH_V2_CLIENT_ID: ${{ secrets.OAUTH_V2_CLIENT_ID }}
      OAUTH_V2_REDIRECT_URL: ${{ secrets.OAUTH_V2_REDIRECT_URL }}
      OAUTH_V2_SCOPES: ${{ secrets.OAUTH_V2_SCOPES }}
      OAUTH_V2_ENDPOINT: ${{ secrets.OAUTH_V2_ENDPOINT }}
      VOLUBA_OAUTH_V2_CLIENT_ID: ${{ secrets.VOLUBA_OAUTH_V2_CLIENT_ID }}
      VOLUBA_OAUTH_V2_REDIRECT_URL: ${{ secrets.VOLUBA_OAUTH_V2_REDIRECT_URL }}
      VOLUBA_OAUTH_V2_SCOPES: ${{ secrets.VOLUBA_OAUTH_V2_SCOPES }}
      VOLUBA_OAUTH_V2_ENDPOINT: ${{ secrets.VOLUBA_OAUTH_V2_ENDPOINT }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run mocha -- './ebrains_services/oauth.spec.js'
    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_OAUTH" ]
        then
          curl "$SIIBRA_MONITORING_OAUTH"
        fi
