# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[iav] [2hr] saneurl api"

on:
  schedule:
    - cron: '14 */2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        api-endpoint: [ 'https://interactive-viewer.apps.hbp.eu', 'https://atlases.ebrains.eu/viewer' ]

    env:
      API_ENDPOINT: ${{ matrix.api-endpoint }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run mocha -- './siibra/explorer/saneUrl.spec.js' --timeout 10000
