# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: "[iav] [2hr] saneurl api"

on:
  schedule:
    - cron: '14 */2 * * *'

env:
  SIIBRA_MONITORING_SANEURL: ${{ secrets.SIIBRA_MONITORING_SANEURL }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        api-endpoint: [ 'https://atlases.ebrains.eu/viewer' ]

    env:
      SIIBRA_EXPLORER_ENDPOINT: ${{ matrix.api-endpoint }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run mocha -- './siibra/explorer/saneUrl.spec.js' --timeout 10000
    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_SANEURL" ]
        then
          curl "$SIIBRA_MONITORING_SANEURL"
        fi
