name: "[kg/query] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  SIIBRA_MONITORING_KG_QUERY_INSTANCE: ${{ secrets.SIIBRA_MONITORING_KG_QUERY_INSTANCE }}
  OAUTH_V2_SA_CLIENT_ID: ${{ secrets.OAUTH_V2_SA_CLIENT_ID }}
  OAUTH_V2_SA_CLIENT_SECRET: ${{ secrets.OAUTH_V2_SA_CLIENT_SECRET }}
  OAUTH_V2_SA_ENDPOINT: ${{ secrets.OAUTH_V2_SA_ENDPOINT }}
  OAUTH_V2_SA_SCOPES: ${{ secrets.OAUTH_V2_SA_SCOPES }}
jobs:
  specific-query:
    runs-on: ubuntu-latest

    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        kg_version: ['v3']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Testing KG ${{ matrix.kg_version }}
      run: |
        npm i
        npm run mocha -- './kg-query/${{ matrix.kg_version }}/index.js' --timeout 5000

  report-to-uptime:
    needs: specific-query
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: Report to monitoring
      if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_KG_QUERY_INSTANCE" ]
        then
          curl "$SIIBRA_MONITORING_KG_QUERY_INSTANCE"
        fi
