# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Monitoring KG Dataset Preview Service

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
        nehubaui-branch: [ master, staging, dev ]
        ds-preview: [ [v0, 'https://hbp-kg-dataset-previewer.apps.hbp.eu/datasetPreview'], [ v2, https://hbp-kg-dataset-previewer.apps.hbp.eu/v2 ] ]
    env:
      DS_PREVIEW_URL: ${{ matrix.ds-preview[1] }}
      DS_PREVIEW_URL_VERSION: ${{ matrix.ds-preview[0] }}
      NEHUBA_UI_BRANCH: ${{ matrix.nehubaui-branch }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run mocha -- './kgService/**.js'
