# TODO deprecate after PLI is ported

name: '[iav-dep] [1hr] kg DS preview'

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]
        nehubaui-branch: [ master, staging ]
        ds-preview-version: [ v2 ]
        include:
        - ds-preview-version: v2
          ds-preview-url: 'https://hbp-kg-dataset-previewer.apps.hbp.eu/v2'
            
    env:
      DS_PREVIEW_URL: ${{ matrix.ds-preview-url }}
      DS_PREVIEW_URL_VERSION: ${{ matrix.ds-preview-version }}
      NEHUBA_UI_BRANCH: ${{ matrix.nehubaui-branch }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run mocha -- './kgService/**.js' --timeout 5000 --retries 5
