name: "[siibra-dep] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  SIIBRA_MONITORING_SIIBRA_DEPENDENCIES: ${{ secrets.SIIBRA_MONITORING_SIIBRA_DEPENDENCIES }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ENDPOINT:
        - https://siibra-spatial-backend.apps.tc.humanbrainproject.eu/
        - https://hbp-spatial-backend.apps.hbp.eu/

    env:
      ENDPOINT: ${{ matrix.ENDPOINT }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
    - name: 'Install test dependencies'
      run: pip install requests pytest pytest-timeout
    - run: pytest -svvv siibra/deps
    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_SIIBRA_DEPENDENCIES" ]
        then
          curl "$SIIBRA_MONITORING_SIIBRA_DEPENDENCIES"
        fi