name: "[siibra-explorer] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  SIIBRA_MONITORING_EXPLORER: ${{ secrets.SIIBRA_MONITORING_EXPLORER }}

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        end-point: [ 'https://atlases.ebrains.eu/viewer' ]
    env:
      SIIBRA_EXPLORER_ENDPOINT: ${{ matrix.end-point }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        npm i
        npm run mocha -- './siibra/explorer/index.spec.js' --timeout 5000

    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_EXPLORER" ]
        then
          curl "$SIIBRA_MONITORING_EXPLORER"
        fi