name: "[siibra-dep] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  SIIBRA_MONITORING_SIIBRA_DEPENDENCIES: ${{ secrets.SIIBRA_MONITORING_SIIBRA_DEPENDENCIES }}

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    env:
      OAUTH_V2_SA_CLIENT_ID: ${{ secrets.OAUTH_V2_SA_CLIENT_ID }}
      OAUTH_V2_SA_CLIENT_SECRET: ${{ secrets.OAUTH_V2_SA_CLIENT_SECRET }}
      OAUTH_V2_SA_ENDPOINT: ${{ secrets.OAUTH_V2_SA_ENDPOINT }}
      OAUTH_V2_SA_SCOPES: ${{ secrets.OAUTH_V2_SA_SCOPES }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm i
    - run: npm run mocha -- './siibra-dep/**/*.spec.js' --timeout 5000
    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_SIIBRA_DEPENDENCIES" ]
        then
          curl "$SIIBRA_MONITORING_SIIBRA_DEPENDENCIES"
        fi