name: "[siibra-explorer] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        end-point: [ 'https://siibra-api-stable.apps.hbp.eu/', 'https://interactive-viewer.apps.hbp.eu/', 'https://atlases.ebrains.eu/viewer']
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: |
        npm i
        SIIBRA_EXPLORER_ENDPOINT=${{ matrix.end-point }} npm run mocha -- './siibra/explorer/index.spec.js' --timeout 5000

