name: "[siibra-api] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'
env:
  SIIBRA_API_E2E_BASE_URL: https://siibra-api-stable.apps.hbp.eu

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        repository: 'fzj-inm1-bda/siibra-api'
        ref: 'feat_e2eTests'
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
    - name: Run test
      run: |
        pytest ./e2e_tests/