name: "[siibra-explorer] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        end-point: [ 'https://atlases.ebrains.eu/viewer/', 'https://siibra-explorer.apps.tc.humanbrainproject.eu/viewer/' ]
    env:
      SIIBRA_EXPLORER_ENDPOINT: ${{ matrix.end-point }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: pytest siibra/explorer