name: "[siibra-dep] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # since both hostname funnel to the same service, max parallel set to 1 to ensure the endpoint is not hammered
      max-parallel: 1
      matrix:
        ENDPOINT:
        - https://siibra-spatial-backend.apps.tc.humanbrainproject.eu/
        - https://hbp-spatial-backend.apps.hbp.eu/

    env:
      ENDPOINT: ${{ matrix.ENDPOINT }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: 'Install test dependencies'
      run: pip install requests pytest pytest-timeout
    - run: pytest -svvv siibra/deps