name: "[siibra-api] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'
env:
  SIIBRA_API_E2E_BASE_URL: https://siibra-api-stable.apps.hbp.eu
  SIIBRA_MONITORING_SIIBRA_API: ${{ secrets.SIIBRA_MONITORING_SIIBRA_API }}
  

jobs:

  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        use-cache: ["true", "false"]
        version: ['v1']
    env:
      USE_CACHE: ${{ matrix.use-cache }}
      
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        python -m pip install pytest requests
    - name: Run test
      run: |
        pytest ./siibra-api/${{ matrix.version }}
    - if: success()
      run: |
        if [ ! -z "$SIIBRA_MONITORING_SIIBRA_API" ]
        then
          curl "$SIIBRA_MONITORING_SIIBRA_API"
        fi