name: "[siibra-data] [10min]"

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  REMOTE_METRIC_PATH: 'metrics/datavm.txt'
  NG_PROFILE_FILE_TO_WRITE: 'datavm.txt'
  DETAIL_FLAG: "1"  
  EBRAINS_SA_CLIENT_ID: ${{ secrets.EBRAINS_SA_CLIENT_ID }}
  EBRAINS_SA_CLIENT_SECRET: ${{ secrets.EBRAINS_SA_CLIENT_SECRET }}
jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.10'
    - name: 'Download existing metric, if available'
      run: |
        curl -L \
          --output ${{ env.NG_PROFILE_FILE_TO_WRITE }} \
          https://data-proxy.ebrains.eu/api/v1/buckets/reference-atlas-data/${{ env.REMOTE_METRIC_PATH }}
        
    - run: pip install requests pytest neuroglancer-scripts tqdm pytest-timeout
    - run: |
        export RUN_ID=${{ github.run_number }}
        pytest -vvv siibra/data
    - if: always()
      uses: "./.github/actions/upload_dataproxy"
      with:
        upload-file: ${{ env.NG_PROFILE_FILE_TO_WRITE }}
        bucket-name: reference-atlas-data
        dest-path: ${{ env.REMOTE_METRIC_PATH }}
        client-id: ${{ env.EBRAINS_SA_CLIENT_ID }}
        client-secret: ${{ env.EBRAINS_SA_CLIENT_SECRET }}
