name: "[test-upload]"

on: [push]

env:
  # voluba sa
  EBRAINS_SA_CLIENT_ID: ${{ secrets.EBRAINS_SA_CLIENT_ID }}
  EBRAINS_SA_CLIENT_SECRET: ${{ secrets.EBRAINS_SA_CLIENT_SECRET }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: "echo 'hello world' >> foo_test.txt"
    - uses: "./.github/actions/upload_dataproxy"
      with:
        upload-file: foo_test.txt
        bucket-name: reference-atlas-data
        dest-path: temp/foo_test.txt
        client-id: ${{ env.EBRAINS_SA_CLIENT_ID }}
        client-secret: ${{ env.EBRAINS_SA_CLIENT_SECRET }}
